name: build-mosrk-launcher

on: [push]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup .net
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Setup dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build MOSRK Launcher
      - name: Build
        run: dotnet publish -c Release --no-restore

      # Upload build artifact
      - uses: actions/upload-artifact@v3
        with:
          name: MOSRK_Launcher
          path: D:\a\MOS-RK_Launcher\MOSRK_Launcher\bin\Release\net6.0-windows\win-x86\publish\MOSRK_Launcher.exe
